-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_throttlespam_ip`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_throttlespam_ip
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_throttlespam_ip` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique ThrottleSpamIp ID',
     `ip_address` varchar(255) NOT NULL   COMMENT 'IP address used',
     `access_date` timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP COMMENT 'When the IP address accessed',
     `contribution_id` int unsigned    COMMENT 'FK to Contribution' 
,
        PRIMARY KEY (`id`)
 
    ,     INDEX `index_ip_address`(
        ip_address
  )
  
,          CONSTRAINT FK_civicrm_throttlespam_ip_id FOREIGN KEY (`id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE CASCADE  
)    ;

 